# Generated by Django 3.2 on 2022-06-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
